Repository lablabs/ansible-role-rke2, pull requests merged in 2023-11, with the labels that each got.

#167 Kube VIP improvements
  README.md
  defaults/main.yml
  templates/kube-vip/kube-vip.yml.j2
Labels: enhancement

#168 feat: Add ability to restore etcd backup from s3 to a cluster with a different name
  tasks/first_server.yml
Labels: enhancement

#171 Add the ability to customize the kube-controller-manager and kube-scheduler arguments
  README.md
  defaults/main.yml
  templates/config.yaml.j2
Labels: enhancement

#173 Copy kube-vip manifests before connecting to first node
  tasks/main.yml
Labels: bug

#174 fix: role downloads badge
  README.md
Labels: documentation
