Repository lablabs/ansible-role-rke2, pull requests merged in 2023-12, with the labels that each got.

#177 Fix RKE2 services restart when configuration changes
  tasks/first_server.yml
  tasks/main.yml
  tasks/remaining_nodes.yml
  tasks/standalone.yml
Labels: enhancement

#180 bug fix to tasks/main.yml
  tasks/main.yml
Labels: bug

#182 Add debug mode
  README.md
  defaults/main.yml
  templates/config.yaml.j2
Labels: enhancement

#183 Improve rolling restart version detection
  handlers/main.yml
  tasks/change_config.yml
  tasks/first_server.yml
  tasks/main.yml
  tasks/remaining_nodes.yml
  tasks/rke2.yml
  tasks/rolling_restart.yml
  tasks/standalone.yml
  vars/main.yml
Labels: bug

#184 update links and add the example to specify the address to advertise
  README.md
  defaults/main.yml
Labels: documentation

#185 Implement #179, add rke2_kubevip_args variable to customize kubevip
  README.md
  defaults/main.yml
  templates/kube-vip/kube-vip.yml.j2
Labels: enhancement

#186 feat: kube vip cloud provider image
  README.md
  defaults/main.yml
  templates/kube-vip/kube-vip-cloud-controller.yml.j2
Labels: enhancement
