Repository lablabs/ansible-role-rke2, pull requests merged in 2023-10, with the labels that each got.

#156 fix /usr/local/bin/rke2: No such file or directory
  tasks/rke2.yml
Labels: bug

#161 fix: badges and links to new ansible galaxy
  README.md
Labels: documentation

#164 fix: ansible galaxy gha
  .github/workflows/galaxy.yml
Labels: CI

#165 decrease permissions config.yaml and registries.yaml
  tasks/first_server.yml
  tasks/remaining_nodes.yml
  tasks/standalone.yml
Labels: bug
