Repository lablabs/ansible-role-rke2, pull requests merged in 2024-05, with the labels that each got.

#213 Add partition check for /usr/local
  tasks/cis.yml
Labels: bug

#216 Allow configuration of nginx ingress controller
  README.md
  defaults/main.yml
  tasks/ingress-nginx.yml
  tasks/main.yml
  templates/ingress-nginx-config.yml.j2
Labels: enhancement

#217 Fix typo in rke2_cloud_provider_name value
  README.md
Labels: documentation

#218 Run ansible-lint in CI and fix issue
  .github/workflows/lint.yml
  tasks/first_server.yml
Labels: bug

#221 fix: unquoted wildcard in mirror config
  templates/registries.yaml.j2
Labels: bug

#219 Fix removing old nodes after restore if rke2-server already started
  tasks/first_server.yml
  tasks/first_server_restore.yml
  tasks/main.yml
Labels: bug

#222 Add editorconfig
  .editorconfig
Labels: CI

#223 Fix separate partition check
  tasks/cis.yml
Labels: bug
