Repository lablabs/ansible-role-rke2, pull requests merged in 2024-10, with the labels that each got.

#249 fix: Change pod readiness check mechanism
  tasks/change_config.yml
  tasks/rolling_restart.yml
Labels: bug

#251 add environment INSTALL_RKE2_TYPE
  tasks/rke2.yml
Labels: bug

#252 add config option: selinux
  README.md
  defaults/main.yml
  templates/config.yaml.j2
Labels: enhancement

#264 fix linting
  templates/config.yaml.j2
Labels: CI

#257 remove old nodes when restoring etcd
  tasks/first_server.yml
Labels: enhancement

#258 fix spelling error with backwards compatiblity
  README.md
  defaults/main.yml
  molecule/cluster/converge.yml
  molecule/default/converge.yml
  molecule/ha_cluster/converge.yml
  molecule/ha_cluster_kubevip/converge.yml
  templates/config.yaml.j2
Labels: bug

#259 rke2 cni is a list
  README.md
  molecule/ha_cluster_kubevip/converge.yml
Labels: bug

#261 rke2_type can be inferred by what group the host is in.
  README.md
  defaults/main.yml
Labels: enhancement
