Repository lablabs/ansible-role-rke2, pull requests merged in 2024-06, with the labels that each got.

#224 fix: Include ingress-nginx.yml only if rke2_ingress_nginx_values is not empty
  tasks/main.yml
Labels: bug

#225 ci: fix ansible-lint
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .yamllint
  README.md
  molecule/cluster/prepare.yml
  molecule/default/prepare.yml
  molecule/ha_cluster/prepare.yml
  molecule/ha_cluster_kubevip/prepare.yml
Labels: CI

#226 feat: use ansible.builtin.dnf module
  tasks/keepalived.yml
Labels: enhancement

#227 feat: add dependabot
  .github/dependabot.yml
Labels: CI

#232 feat: add configuation option for cluster-domain
  README.md
  defaults/main.yml
  templates/config.yaml.j2
Labels: enhancement
