Repository lablabs/ansible-role-rke2, pull requests merged in 2024-02, with the labels that each got.

#194 feat: Configure default prometheus port in kube vip
  README.md
  defaults/main.yml
  templates/kube-vip/kube-vip.yml.j2
Labels: enhancement

#196 feat: Added option to customize kubelet arguments
  README.md
  defaults/main.yml
  templates/config.yaml.j2
Labels: enhancement

#197 Minor typo fixes
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#199 Set permissions for downloaded kubeconf
  tasks/summary.yml
Labels: bug

#192 adding kubevip service election
  README.md
  defaults/main.yml
  templates/kube-vip/kube-vip.yml.j2
Labels: enhancement

#201 bug: wrong variable type for containerPort
  README.md
  defaults/main.yml
  templates/kube-vip/kube-vip.yml.j2
Labels: bug
